#!/usr/bin/env bash
BAIZEL_DIR="$(dirname "${BASH_SOURCE[0]:-${(%):-%x}}")/.baizel"



### Baizel Build System for Java.
### On demand downloads and updates local clone of Baizel to <PROJECT_ROOT>/.baizel, where it bootstraps.
### See .baizel/bin/baizel for full documentation.
function main() {
	local baizelVersion="2b42fc0b2c632ab78bba534166e7d7d9bcdbbc04"
	local baizelOrigin="https://github.com/adamg-nl/baizel.git"



	local currentVersion=$(cat "${BAIZEL_DIR}/.git/refs/heads/main" 2>/dev/null || true)
	if [[ ${currentVersion} == "" ]]; then
		echo "Installing the Baizel Build System for Java..." 1>&2
		mkdir "${BAIZEL_DIR}"
		git clone "${baizelOrigin}" "${BAIZEL_DIR}"
	fi
	if [[ ${currentVersion} != ${baizelVersion} ]]; then
		echo "Updating the Baizel Build System for Java from ${currentVersion} to ${baizelVersion}..." 1>&2
		git -C "${BAIZEL_DIR}" clean -dfX

		local currentOrigin=$(git -C "${BAIZEL_DIR}" remote get-url origin)
		if [[ ${currentOrigin} != ${baizelOrigin} ]]; then
			git -C "${BAIZEL_DIR}" remote add origin "${baizelOrigin}"
            git -C "${BAIZEL_DIR}" remote set-url origin "${baizelOrigin}"
		fi

		git -C "${BAIZEL_DIR}" fetch origin "${baizelVersion}"
		git -C "${BAIZEL_DIR}" reset --hard FETCH_HEAD
	fi
	source "${BAIZEL_DIR}/bin/baizel"
	unset BAIZEL_DIR
}



main "${@}"
