module nl.adamg.baizel.internal.bootstrap {
    exports nl.adamg.baizel.internal.bootstrap;
    requires nl.adamg.baizel.internal.bootstrap.io;
    requires nl.adamg.baizel.internal.bootstrap.java;
    requires nl.adamg.baizel.internal.bootstrap.javadsl;
    requires nl.adamg.baizel.internal.bootstrap.util;
    requires java.compiler;
    requires java.logging;
    requires jdk.compiler;
    //baizel// requires org.apache.httpcomponents.httpclient;
    //baizel// requires org.apache.httpcomponents.httpcore;
    //baizel// requires org.eclipse.aether;
    //baizel// requires org.eclipse.aether.connector.basic;
    //baizel// requires org.eclipse.aether.impl;
    //baizel// requires org.eclipse.aether.internal.impl;
    //baizel// requires org.apache.maven.resolver.maven.resolver.named.locks;
    //baizel// requires org.eclipse.aether.spi;
    //baizel// requires org.apache.maven.resolver.maven.resolver.transport.file;
    //baizel// requires org.apache.maven.resolver.maven.resolver.transport.http;
    //baizel// requires org.apache.maven.resolver.maven.resolver.util;
    //baizel// requires org.apache.maven.maven.artifact;
    //baizel// requires org.apache.maven.maven.builder.support;
    //baizel// requires org.apache.maven.maven.model.builder;
    //baizel// requires org.apache.maven.maven.model;
    //baizel// requires org.apache.maven.repository.internal;
    //baizel// requires org.codehaus.plexus.plexus;
    //baizel// requires org.codehaus.plexus.plexus.utils;
    //baizel// requires org.slf4j.jcl.over.slf4j;
    //baizel// requires org.slf4j.slf4j.api;
    //baizel// requires org.slf4j.slf4j.simple;
}
